# Generated by Django 3.0.6 on 2020-05-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('app_name', 'APP_NAME')], max_length=100, unique=True)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
